# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0003_auto_20170110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ActiveFrom',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='ActiveUntil',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
