# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0004_auto_20170110_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ActiveUntil',
        ),
        migrations.AlterField(
            model_name='author',
            name='ActiveFrom',
            field=models.IntegerField(default=1),
        ),
    ]
