# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0005_auto_20170110_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ActiveFrom',
            field=models.FloatField(default=0),
        ),
    ]
