# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0006_auto_20170110_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ActiveFrom',
        ),
    ]
