# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='PubYear',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='AddedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='NPrints',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GfLib.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='TimesBorrowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
