# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GfLib', '0003_auto_20170115_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='AddedDate',
            new_name='addedDate',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='PubYear',
            new_name='pubYear',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Status',
        ),
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
